### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sinamoghaddas** [snapp-incubator/ghodrat#2]
Can you help me with this error?

```
root@dadb8ebad7a4:/go/ghodrat# ./ghodrat janus --audio-file /go/ghodrat/static/audio.ogg --url ws://192.168.1.2:8188/ --call-count 2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x86446e]

goroutine 40 [running]:
github.com/pion/webrtc/v3.(*TrackLocalStaticSample).WriteSample(0x0, {{0xc0005521c0, 0x3f, 0x3f}, {0x0, 0x0, 0x0}, 0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/pion/webrtc/v3@v3.0.32/track_local_static.go:249 +0x2e
github.com/snapp-incubator/ghodrat/internal/webrtc.(*Call).StreamAudioFile(0xc0002898f0, {0x7fffad64aecc, 0x0})
	/go/ghodrat/internal/webrtc/handle.go:59 +0x2d1
github.com/snapp-incubator/ghodrat/cmd/janus.run.func2()
	/go/ghodrat/cmd/janus/main.go:73 +0x3b
created by github.com/snapp-incubator/ghodrat/cmd/janus.run
	/go/ghodrat/cmd/janus/main.go:72 +0x845
```

**Comment by 1995parham** [comment]
Hi :wave: 
Sorry for the late reply and thanks for using Ghodrat.

we are switching to YAML based configuration so the flags will be deprecated. are run this command in a docker? and can you provide us more information by trying our develop branch?

**Comment by mohammadne** [comment]
I think it's now has been fixed
if you have any problem please reopen the issue
thanks
